carts/urls.py
from os import name
from django.urls import path
from . import views
from .views import (
    ItemDetailView,
    CheckoutView,
    
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,

    AddCouponView,
    RequestRefundView,
    add_to_index,
    remove_from_index,
)

urlpatterns = [
    
    path('add_to_index/<slug>/', add_to_index, name='add_to_index'),
    path('remove_from_index/<slug>/', remove_from_index, name='remove_from_index'),


    

    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('cart/', OrderSummaryView.as_view(), name='cart'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('Review_rate/<int:id>/', views.Review_rate, name='Review_rate'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),

    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    
]

payment/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('khalti',views.khalti,name='khalti')

    ]

srk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('product.urls')),
    path('payment/', include('payment.urls')),
    path('carts/', include('carts.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

print(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

carts/models.py
from random import choice
from django.db import models
from django.conf import settings
from django.db.models import fields
from django.shortcuts import reverse
from django.db.models.signals import post_save
from PIL import Image
from django.forms import ModelForm
ADDRESS_CHOICES = (
    ('S', 'Shipping'),
)

image_choice = {
    ('hot_item', 'hot_item'),
    ('best_sale', 'best_sale'),
    ('top_view', 'top_view'),
    ('on_sale', 'on_sale'),
}

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Brand(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    

class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


# class Item_choice(models.Model):
#     name = models.CharField(max_length=200)
#     def __str__(self):
#         return self.name

class Item(models.Model):
    choice = models.CharField(max_length=200,choices=image_choice, blank=True)
    title = models.CharField(max_length=100)
    price = models.IntegerField()
    discount_price = models.IntegerField(blank=True, null=True)
    category = models.ForeignKey(Category, null=True,on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, null=True,on_delete=models.CASCADE)
    slug = models.SlugField()
    stock = models.IntegerField()
    description = models.TextField()
    image = models.ImageField(upload_to='media', null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("product", kwargs={
            'slug': self.slug
        })

    def add_to_index_url(self):
        return reverse("add_to_index", kwargs={
            'slug': self.slug
        })

    def remove_from_index_url(self):
        return reverse("product:remove_from_index", kwargs={
            'slug': self.slug
        })
    
    def get_add_to_cart_url(self):
        return reverse("add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("remove-from-cart", kwargs={
            'slug': self.slug
        })

    
class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    phone_number = models.IntegerField()
    gmail = models.EmailField(max_length=50)
    country = models.CharField(max_length=50)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)


class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    product = models.ForeignKey(Item, on_delete= models.CASCADE)
    comment = models.TextField(max_length=250)
    rate = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

payment/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Khalti(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='media/khalti')
    Refrence_Code = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.user.username

carts/forms.py
from re import I
from carts.models import Review
from django import forms
from django.forms import Form
from django.forms import ModelForm

PAYMENT_CHOICES = (
    ('E', 'Esewa'),
    ('K', 'Khalti'),
    ('I', 'Imepay'),
)


class CheckoutForm(forms.Form):
    shipping_first_name = forms.CharField(max_length=50)
    shipping_last_name = forms.CharField(max_length=50)
    shipping_address = forms.CharField(required=False)
    shipping_address2 = forms.CharField(required=False)
    shipping_country = forms.CharField(max_length=50)
    shipping_zip = forms.CharField(required=False)
    shipping_phone_number = forms.IntegerField()
    shipping_gmail = forms.EmailField(max_length=50)

    set_default_shipping = forms.BooleanField(required=False)
    use_default_shipping = forms.BooleanField(required=False)

    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect, choices=PAYMENT_CHOICES)


class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Promo code',
        'aria-label': 'Recipient\'s username',
        'aria-describedby': 'basic-addon2'
    }))


class RefundForm(forms.Form):
    ref_code = forms.CharField()
    message = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 4
    }))
    email = forms.EmailField()


class PaymentForm(forms.Form):
    stripeToken = forms.CharField(required=False)
    save = forms.BooleanField(required=False)
    use_default = forms.BooleanField(required=False)


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['comment','rate']

payment/forms.py
from django import forms
from.models import Khalti

class Khaltiform(forms.ModelForm):
    class Meta:
        model = Khalti
        fields = ['image','Refrence_Code']

payment/views.py
from django.contrib.auth.models import User
from django.shortcuts import render,redirect
from django.views.generic import CreateView

from  .forms import Khaltiform
from .models import Khalti
# Create your views here.

def khalti(request):

    # if request.method == 'POST':
    #     khalti = Khaltiform(request.POST, request.FILES)
    #     userprofile = Khalti.objects.get(user=self.request.user)
    #     if khalti.is_valid():
    #         khalti.save()
    #         return redirect('/')
    # else:
    #     khalti = Khaltiform()
    # context = {'khalti':khalti}
    return render(request, 'payment.html')

templates/aboutus.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
	
	<!-- Breadcrumbs -->
	<div class="breadcrumbs">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="bread-inner">
						<ul class="bread-list">
							<li><a href="index1.html">Home<i class="ti-arrow-right"></i></a></li>
							<li class="active"><a href="blog-single.html">About Us</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Breadcrumbs -->
	
	<!-- About Us -->
	<section class="about-us section">
			<div class="container">
				<div class="row">
					<div class="col-lg-6 col-12">
						<div class="about-content">
							<h3>Welcome To <span>Eshop</span></h3>
							<p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. sed ut perspiciatis unde sunt in culpa qui officia deserunt mollit anim id est laborum.  sed ut perspiciatis unde omnis iste natus error sit voluptatem Excepteu </p>
							<p>sunt in culpa qui officia deserunt mollit anim id est laborum. sed ut perspiciatis Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. sed ut perspi deserunt mollit anim id est laborum. sed ut perspi.</p>
							<div class="button">
								<a href="blog.html" class="btn">Our Blog</a>
								<a href="contact.html" class="btn primary">Contact Us</a>
							</div>
						</div>
					</div>
					<div class="col-lg-6 col-12">
						<div class="about-img overlay">
							<div class="button">
								<a href="https://www.youtube.com/watch?v=nh2aYrGMrIE" class="video video-popup mfp-iframe"><i class="fa fa-play"></i></a>
							</div>
							<img src="images/about.jpg" alt="#">
						</div>
					</div>
				</div>
			</div>
	</section>
	<!-- End About Us -->
	
	<!-- Start Team -->
	<section id="team" class="team section">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="section-title">
						<h2>Our Expert Team</h2>
						<p>Business consulting excepteur sint occaecat cupidatat consulting non proident, sunt in culpa qui officia deserunt laborum market. </p>
					</div>
				</div>
			</div>
			<div class="row">
				<!-- Single Team -->
				<div class="col-lg-3 col-md-6 col-12">
					<div class="single-team">
						<!-- Image -->
						<div class="image">
							<img src="images/team/team1.jpg" alt="#">
						</div>
						<!-- End Image -->
						<div class="info-head">
							<!-- Info Box -->
							<div class="info-box">
								<h4 class="name"><a href="#">Dahlia Moore</a></h4>
								<span class="designation">Senior Manager</span>
							</div>
							<!-- End Info Box -->
							<!-- Social -->
							<div class="social-links">
								<ul class="social">
									<li><a href="#"><i class="fa fa-facebook-f"></i></a></li>
									<li><a href="#"><i class="fa fa-twitter"></i></a></li>
									<li><a href="#"><i class="fa fa-behance"></i></a></li>
									<li><a href="#"><i class="fa fa-instagram"></i></a></li>
								</ul>
							</div>
							<!-- End Social -->
						</div>
					</div>
				</div>	
				<!-- End Single Team -->
				<div class="col-lg-3 col-md-6 col-12">
					<div class="single-team">
						<!-- Image -->
						<div class="image">
							<img src="images/team/team2.jpg" alt="#">
						</div>
						<!-- End Image -->
						<div class="info-head">
							<!-- Info Box -->
							<div class="info-box">
								<h4 class="name"><a href="#">Jhone digo</a></h4>
								<span class="designation">Markeitng</span>
							</div>
							<!-- End Info Box -->
							<!-- Social -->
							<div class="social-links">
								<ul class="social">
									<li><a href="#"><i class="fa fa-facebook-f"></i></a></li>
									<li><a href="#"><i class="fa fa-twitter"></i></a></li>
									<li><a href="#"><i class="fa fa-behance"></i></a></li>
									<li><a href="#"><i class="fa fa-instagram"></i></a></li>
								</ul>
							</div>
							<!-- End Social -->
						</div>
					</div>
				</div>	
				<!-- End Single Team -->
				<div class="col-lg-3 col-md-6 col-12">
					<div class="single-team">
						<!-- Image -->
						<div class="image">
							<img src="images/team/team3.jpg" alt="#">
						</div>
						<!-- End Image -->
						<div class="info-head">
							<!-- Info Box -->
							<div class="info-box">
								<h4 class="name"><a href="#">Zara tingo</a></h4>
								<span class="designation">Web Developer</span>
							</div>
							<!-- End Info Box -->
							<!-- Social -->
							<div class="social-links">
								<ul class="social">
									<li><a href="#"><i class="fa fa-facebook-f"></i></a></li>
									<li><a href="#"><i class="fa fa-twitter"></i></a></li>
									<li><a href="#"><i class="fa fa-behance"></i></a></li>
									<li><a href="#"><i class="fa fa-instagram"></i></a></li>
								</ul>
							</div>
							<!-- End Social -->
						</div>
					</div>
				</div>	
				<!-- End Single Team -->
				<div class="col-lg-3 col-md-6 col-12">
					<div class="single-team">
						<!-- Image -->
						<div class="image">
							<img src="images/team/team4.jpg" alt="#">
						</div>
						<!-- End Image -->
						<div class="info-head">
							<!-- Info Box -->
							<div class="info-box">
								<h4 class="name"><a href="#">David Zone</a></h4>
								<span class="designation">SEO Expert</span>
							</div>
							<!-- End Info Box -->
							<!-- Social -->
							<div class="social-links">
								<ul class="social">
									<li><a href="#"><i class="fa fa-facebook-f"></i></a></li>
									<li><a href="#"><i class="fa fa-twitter"></i></a></li>
									<li><a href="#"><i class="fa fa-behance"></i></a></li>
									<li><a href="#"><i class="fa fa-instagram"></i></a></li>
								</ul>
							</div>
							<!-- End Social -->
						</div>
					</div>
				</div>	
				<!-- End Single Team -->
			</div>	
		</div>
	</section>
	<!--/ End Team Area -->
	
	<!-- Start Shop Services Area -->
	<section class="shop-services section">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-6 col-12">
					<!-- Start Single Service -->
					<div class="single-service">
						<i class="ti-rocket"></i>
						<h4>Free shiping</h4>
						<p>Orders over $100</p>
					</div>
					<!-- End Single Service -->
				</div>
				<div class="col-lg-3 col-md-6 col-12">
					<!-- Start Single Service -->
					<div class="single-service">
						<i class="ti-reload"></i>
						<h4>Free Return</h4>
						<p>Within 30 days returns</p>
					</div>
					<!-- End Single Service -->
				</div>
				<div class="col-lg-3 col-md-6 col-12">
					<!-- Start Single Service -->
					<div class="single-service">
						<i class="ti-lock"></i>
						<h4>Sucure Payment</h4>
						<p>100% secure payment</p>
					</div>
					<!-- End Single Service -->
				</div>
				<div class="col-lg-3 col-md-6 col-12">
					<!-- Start Single Service -->
					<div class="single-service">
						<i class="ti-tag"></i>
						<h4>Best Peice</h4>
						<p>Guaranteed price</p>
					</div>
					<!-- End Single Service -->
				</div>
			</div>
		</div>
	</section>
	<!-- End Shop Services Area -->
	
	<!-- Start Shop Newsletter  -->
	<section class="shop-newsletter section">
		<div class="container">
			<div class="inner-top">
				<div class="row">
					<div class="col-lg-8 offset-lg-2 col-12">
						<!-- Start Newsletter Inner -->
						<div class="inner">
							<h4>Newsletter</h4>
							<p> Subscribe to our newsletter and get <span>10%</span> off your first purchase</p>
							<form action="mail/mail.php" method="get" target="_blank" class="newsletter-inner">
								<input name="EMAIL" placeholder="Your email address" required="" type="email">
								<button class="btn">Subscribe</button>
							</form>
						</div>
						<!-- End Newsletter Inner -->
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End Shop Newsletter -->
{% endblock %}

templates/checkout.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

		<!-- Breadcrumbs -->
<div class="breadcrumbs" xmlns="http://www.w3.org/1999/html">
			<div class="container">
				<div class="row">
					<div class="col-12">
						<div class="bread-inner">
							<ul class="bread-list">
								<li><a href="index1.html">Home<i class="ti-arrow-right"></i></a></li>
								<li class="active"><a href="blog-single.html">Checkout</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- End Breadcrumbs -->

		<!-- Start Checkout -->
		<section class="shop checkout section">
			<div class="container">
					<div class="row">
						<div class="col-lg-8 col-12">
							<div class="checkout-form">
								<h2>Make Your Checkout Here</h2>
								<p>Please Shipping address in order to checkout more quickly</p>
								{% if messages %}
								{% for message in messages %}
								<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
								  {{ message }}
								  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								  </button>
								</div>
								{% endfor %}
								{% endif %}
								<!-- Form -->
								<form class="form" method="post">
									{% csrf_token %}									
									<div class="hideable_shipping_form">
										<div class="row">
											<!-- {{form.as_p}} -->
											<div class="col-lg-6 col-md-6 col-12">
												
												<div class="form-group">
													<label>First Name<span>*</span></label>
													<input type="text" placeholder="First Name" id='id_shipping_first_name' name='shipping_first_name'>
												</div>
											</div>
											<div class="col-lg-6 col-md-6 col-12">
												<div class="form-group">
													<label>Last Name<span>*</span></label>
													<input type="text" placeholder="Last Name" id='id_shipping_last_name' name='shipping_last_name'>
												</div>
											</div>
											<div class="col-lg-6 col-md-6 col-12">
												<div class="form-group">
													<label>Email Address<span>*</span></label>
													<input type="text" placeholder="Email Address" id='id_shipping_gmail' name='shipping_gmail'>
												</div>
											</div>
											<div class="col-lg-6 col-md-6 col-12">
												<div class="form-group">
													<label>Phone Number<span>*</span></label>
													<input type="text" placeholder="Phone Number" id='id_shipping_phone_number' name='shipping_phone_number'>
												</div>
											</div>
											<div class="col-lg-6 col-md-6 col-12">
												<div class="form-group">
													<label>Address 1<span>*</span></label>
													<input type="text" placeholder="Address 1" id='id_shipping_address' name='shipping_address'>
												</div>
											</div>
											<div class="col-lg-6 col-md-6 col-12">
												<div class="form-group">
													<label>Address 2 <span>*</span></label>
													<input type="text" placeholder="Address 2 " id='id_shipping_address2' name='shipping_address2'>
												</div>
											</div>
											<div class="col-lg-6 col-md-6 col-12">
												<div class="form-group">
													<label>Country<span>*</span></label>
													<input type="text" name="shipping_country" id="id_shipping_country" placeholder="Country">
												</div>
											</div>
											<div class="col-lg-6 col-md-6 col-12">
												<div class="form-group">
													<label>Zip<span>*</span></label>
													<input type="text" id='shipping_zip' name='id_shipping_zip' placeholder="Zip">
												</div>
											</div>
											<div class="col-12">
												<div class="form-group create-account">
													<input type="checkbox" name="set_default_shipping" id="id_set_default_shipping">
													<label class="custom-control-label" for="id_set_default_shipping">Save as default shipping address</label>
												</div>
											</div>
										</div>
									</div>
									<div class="row">
										{% if default_shipping_address %}
												<div class="col-12">
													<div class="form-group create-account">
														<input type="checkbox" name="use_default_shipping" id="use_default_shipping">
														<label class="custom-control-label" for="use_default_shipping">Use default shipping address: 
														{{default_shipping_address.street_address|truncatechars:10 }}</label>
													</div>
												</div>
										{% endif %}
										<!-- Order Widget -->
										<div class="single-widget">
											<h2>Payments</h2>
											<br>
											<div class="col-12">
												{{form.payment_option}}
											</div>
											
										</div>
										<!--/ End Order Widget -->
									</div>
									<div class="container">
										<div class="row">
											<div class="inner">
												<div class="single-widget get-button">
													<div class="col-12">
														<div class="button">
															<button type="submit" class="btn" style="width: 200%;">proceed to checkout</button>
														</div>
													</div>
												</div>
											</div>
										</div>
										
									</div>
								</form>
							<!--/ End Form -->
						</div>
					</div>
					
						<div class="col-lg-4 col-12">
							<div class="order-details">
								{% include 'order_snippet.html' %}
							</div>
							
						</div>
					</div>
				</form>
			</div>
		</section>
		<!--/ End Checkout -->

		<!-- Start Shop Services Area  -->
		<section class="shop-services section home">
			<div class="container">
				<div class="row">
					<div class="col-lg-3 col-md-6 col-12">
						<!-- Start Single Service -->
						<div class="single-service">
							<i class="ti-rocket"></i>
							<h4>Free shiping</h4>
							<p>Orders over $100</p>
						</div>
						<!-- End Single Service -->
					</div>
					<div class="col-lg-3 col-md-6 col-12">
						<!-- Start Single Service -->
						<div class="single-service">
							<i class="ti-reload"></i>
							<h4>Free Return</h4>
							<p>Within 30 days returns</p>
						</div>
						<!-- End Single Service -->
					</div>
					<div class="col-lg-3 col-md-6 col-12">
						<!-- Start Single Service -->
						<div class="single-service">
							<i class="ti-lock"></i>
							<h4>Sucure Payment</h4>
							<p>100% secure payment</p>
						</div>
						<!-- End Single Service -->
					</div>
					<div class="col-lg-3 col-md-6 col-12">
						<!-- Start Single Service -->
						<div class="single-service">
							<i class="ti-tag"></i>
							<h4>Best Peice</h4>
							<p>Guaranteed price</p>
						</div>
						<!-- End Single Service -->
					</div>
				</div>
			</div>
		</section>
		<!-- End Shop Services -->

		<!-- Start Shop Newsletter  -->
		<section class="shop-newsletter section">
			<div class="container">
				<div class="inner-top">
					<div class="row">
						<div class="col-lg-8 offset-lg-2 col-12">
							<!-- Start Newsletter Inner -->
							<div class="inner">
								<h4>Newsletter</h4>
								<p> Subscribe to our newsletter and get <span>10%</span> off your first purchase</p>
								<form action="mail/mail.php" method="get" target="_blank" class="newsletter-inner">
									<input name="EMAIL" placeholder="Your email address" required="" type="email">
									<button class="btn">Subscribe</button>
								</form>
							</div>
							<!-- End Newsletter Inner -->
						</div>
					</div>
				</div>
			</div>
		</section>
		<!-- End Shop Newsletter -->
{% endblock %}
{% block js %}
<script>
	var hideable_shipping_form = $('.hideable_shipping_form');
  
	var use_default_shipping = document.querySelector("input[name=use_default_shipping]");
  
	use_default_shipping.addEventListener('change', function () {
	  if (this.checked) {
		hideable_shipping_form.hide();
	  } else {
		hideable_shipping_form.show();
	  }
	})
  
  </script>
{% endblock %}